version: '3.9'
services:
    apache-levelup:
      container_name: php-levelup
      build: .
      depends_on:
        - db
      ports:
        - 8080:80
      volumes:
        - ./src:/var/www/html
      networks:   # al faltar este dato salta error "Temporary failure in name resolution"
        - network   

    db:
      container_name: mysql_levelup
      image: mysql:5.7
      ports:
        - 3306:3306
      volumes:
        - mysql_levelup:/var/lib/mysql
        - ./levelup.sql:/docker-entrypoint-initdb.d/levelup.sql 
      restart: always
      environment:
        MYSQL_DATABASE: levelup
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_ROOT_PASSWORD: root
      networks:
        - network

networks:
  network:
    driver: bridge

volumes:
  mysql_levelup:
